// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// f_Confidence_band
arma::vec f_Confidence_band(arma::vec vTrue, arma::vec vPred);
RcppExport SEXP _mthesis_f_Confidence_band(SEXP vTrueSEXP, SEXP vPredSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type vTrue(vTrueSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type vPred(vPredSEXP);
    rcpp_result_gen = Rcpp::wrap(f_Confidence_band(vTrue, vPred));
    return rcpp_result_gen;
END_RCPP
}
// f_CalcR
arma::mat f_CalcR(arma::mat Rxx, arma::mat Rxy, arma::mat Ryy, arma::mat Ryx);
RcppExport SEXP _mthesis_f_CalcR(SEXP RxxSEXP, SEXP RxySEXP, SEXP RyySEXP, SEXP RyxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Rxx(RxxSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Rxy(RxySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Ryy(RyySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Ryx(RyxSEXP);
    rcpp_result_gen = Rcpp::wrap(f_CalcR(Rxx, Rxy, Ryy, Ryx));
    return rcpp_result_gen;
END_RCPP
}
// f_hmm
arma::cube f_hmm(arma::cube aData, int iN_lags);
RcppExport SEXP _mthesis_f_hmm(SEXP aDataSEXP, SEXP iN_lagsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube >::type aData(aDataSEXP);
    Rcpp::traits::input_parameter< int >::type iN_lags(iN_lagsSEXP);
    rcpp_result_gen = Rcpp::wrap(f_hmm(aData, iN_lags));
    return rcpp_result_gen;
END_RCPP
}
// f_aData_train_fillC
Rcpp::List f_aData_train_fillC(arma::cube aX, arma::mat mY, int iN_lags, int iN_row);
RcppExport SEXP _mthesis_f_aData_train_fillC(SEXP aXSEXP, SEXP mYSEXP, SEXP iN_lagsSEXP, SEXP iN_rowSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube >::type aX(aXSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mY(mYSEXP);
    Rcpp::traits::input_parameter< int >::type iN_lags(iN_lagsSEXP);
    Rcpp::traits::input_parameter< int >::type iN_row(iN_rowSEXP);
    rcpp_result_gen = Rcpp::wrap(f_aData_train_fillC(aX, mY, iN_lags, iN_row));
    return rcpp_result_gen;
END_RCPP
}
// f_aData_scale_C
Rcpp::List f_aData_scale_C(arma::cube aX);
RcppExport SEXP _mthesis_f_aData_scale_C(SEXP aXSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube >::type aX(aXSEXP);
    rcpp_result_gen = Rcpp::wrap(f_aData_scale_C(aX));
    return rcpp_result_gen;
END_RCPP
}
// f_KalmanFilterC
Rcpp::List f_KalmanFilterC(arma::mat mY, arma::cube aZ, arma::cube aH, arma::cube aT, arma::cube aR, arma::cube aQ, arma::vec vA1, arma::mat mP1, int iJ);
RcppExport SEXP _mthesis_f_KalmanFilterC(SEXP mYSEXP, SEXP aZSEXP, SEXP aHSEXP, SEXP aTSEXP, SEXP aRSEXP, SEXP aQSEXP, SEXP vA1SEXP, SEXP mP1SEXP, SEXP iJSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type mY(mYSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type aZ(aZSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type aH(aHSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type aT(aTSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type aR(aRSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type aQ(aQSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type vA1(vA1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mP1(mP1SEXP);
    Rcpp::traits::input_parameter< int >::type iJ(iJSEXP);
    rcpp_result_gen = Rcpp::wrap(f_KalmanFilterC(mY, aZ, aH, aT, aR, aQ, vA1, mP1, iJ));
    return rcpp_result_gen;
END_RCPP
}
// chol_comp
Rcpp::List chol_comp(arma::mat mX);
RcppExport SEXP _mthesis_chol_comp(SEXP mXSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type mX(mXSEXP);
    rcpp_result_gen = Rcpp::wrap(chol_comp(mX));
    return rcpp_result_gen;
END_RCPP
}
// contains
Rcpp::LogicalVector contains(Rcpp::StringVector vMCS_models, Rcpp::StringVector vModels);
RcppExport SEXP _mthesis_contains(SEXP vMCS_modelsSEXP, SEXP vModelsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::StringVector >::type vMCS_models(vMCS_modelsSEXP);
    Rcpp::traits::input_parameter< Rcpp::StringVector >::type vModels(vModelsSEXP);
    rcpp_result_gen = Rcpp::wrap(contains(vMCS_models, vModels));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mthesis_f_Confidence_band", (DL_FUNC) &_mthesis_f_Confidence_band, 2},
    {"_mthesis_f_CalcR", (DL_FUNC) &_mthesis_f_CalcR, 4},
    {"_mthesis_f_hmm", (DL_FUNC) &_mthesis_f_hmm, 2},
    {"_mthesis_f_aData_train_fillC", (DL_FUNC) &_mthesis_f_aData_train_fillC, 4},
    {"_mthesis_f_aData_scale_C", (DL_FUNC) &_mthesis_f_aData_scale_C, 1},
    {"_mthesis_f_KalmanFilterC", (DL_FUNC) &_mthesis_f_KalmanFilterC, 9},
    {"_mthesis_chol_comp", (DL_FUNC) &_mthesis_chol_comp, 1},
    {"_mthesis_contains", (DL_FUNC) &_mthesis_contains, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_mthesis(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
