# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

f_Confidence_band <- function(vTrue, vPred) {
    .Call(`_mthesis_f_Confidence_band`, vTrue, vPred)
}

f_CalcR <- function(Rxx, Rxy, Ryy, Ryx) {
    .Call(`_mthesis_f_CalcR`, Rxx, Rxy, Ryy, Ryx)
}

f_hmm <- function(aData, iN_lags) {
    .Call(`_mthesis_f_hmm`, aData, iN_lags)
}

f_aData_train_fillC <- function(aX, mY, iN_lags, iN_row) {
    .Call(`_mthesis_f_aData_train_fillC`, aX, mY, iN_lags, iN_row)
}

f_aData_scale_C <- function(aX) {
    .Call(`_mthesis_f_aData_scale_C`, aX)
}

f_KalmanFilterC <- function(mY, aZ, aH, aT, aR, aQ, vA1, mP1, iJ) {
    .Call(`_mthesis_f_KalmanFilterC`, mY, aZ, aH, aT, aR, aQ, vA1, mP1, iJ)
}

chol_comp <- function(mX) {
    .Call(`_mthesis_chol_comp`, mX)
}

contains <- function(vMCS_models, vModels) {
    .Call(`_mthesis_contains`, vMCS_models, vModels)
}

